import { TranslationSet, ServiceDetail, CVExperienceItem } from './types';

export const TRANSLATIONS: Record<'al' | 'en', TranslationSet> = {
  al: {
    navHome: "Kreu",
    navAbout: "Rreth Avokatit",
    navServices: "Shërbimet Ligjore",
    navContact: "Na Kontaktoni",
    navSchedule: "Cakto Takim",
    heroTitle: "Mbrojtje Ligjore me Integritet dhe Ekspertizë",
    heroSubTitle: "Avokat Ernest Shimka",
    heroDescription: "Avokat i specializuar në të Drejtën Tatimore dhe të Punësimit në Shqipëri. Ofrojmë zgjidhje strategjike dhe mbrojtje ligjore për biznese dhe individë me profesionalizëm të lartë.",
    heroCTAContact: "Më Kontakto",
    heroCTASchedule: "Cakto një Takim",
    quoteText: "Ligji nuk duhet të jetë një pengesë për biznesin tuaj, por një mburojë e fuqishme që garanton rritjen dhe stabilitetin e tij.",
    quoteAuthor: "Ernest Shimka",
    aboutTitle: "Rreth Avokatit",
    aboutBadge: "Biografia & Karriera",
    aboutDegree: "Jurist i diplomuar nga Fakulteti i Drejtësisë, Universiteti i Tiranës",
    cvSectionTitle: "Curriculum Vitae",
    cvPersonal: "Të Dhënat Personale",
    cvEducation: "Arsimi",
    cvExperience: "Përvoja Profesionale",
    cvLanguages: "Gjuhët e Huaja",
    cvSkills: "Aftësi & Njohuri",
    cvSpecializations: "Kualifikime",
    cvAftesi: "Aftësi Komunikuese",
    labelName: "Emri i Plotë",
    labelBirth: "Data e Lindjes",
    labelProfession: "Profesioni",
    labelEmail: "Adresa Email",
    labelPhone: "Numri i Telefonit",
    labelLocation: "Adresa / Selia",
    servicesTitle: "Ekspertiza Ligjore",
    servicesBadge: "Shërbimet Tona",
    servicesSubtitle: "Specializuar në dy shtillat kryesore rregullatore të çdo sipërmarrjeje dhe marrëdhënieje profesionale.",
    taxLawTitle: "Të Drejtat Tatimore",
    taxLawDesc: "Këshillim tatimor strategjik për të optimizuar strukturën tuaj financiare dhe për të mbrojtur biznesin tuaj nga rreziqet ligjore.",
    employmentLawTitle: "Të Drejtat e Punësimit",
    employmentLawDesc: "Mbrojtje e plotë ligjore për marrëdhëniet e punës, kontratat, pajtueshmërinë rregullatore dhe zgjidhjen e konflikteve kolektive apo individuale.",
    viewMoreDetails: "Lexo artikujt e plotë",
    contactTitle: "Na Kontaktoni",
    contactBadge: "Informacion Kontakti",
    contactSubtitle: "Jemi në dispozicionin tuaj për çdo pyetje apo konsulencë ligjore. Na shkruani direct ose na telefononi.",
    formName: "Emri Juaj",
    formEmail: "Email",
    formPhone: "Telefon",
    formSubject: "Subjekti / Çështja",
    formMessage: "Mesazhi / Përshkrimi i çështjes",
    formSubmit: "Dërgo Mesazhin",
    formSubmitting: "Duke u dërguar...",
    formSuccessMessage: "Mesazhi juaj u dërgua me sukses! Avokat Ernest Shimka do t'ju kontaktojë shumë shpejt.",
    formErrorMessage: "Ndodhi një gabim gjatë dërgimit. Ju lutem provoni përsëri.",
    scheduleTitle: "Cakto një Konsulencë",
    scheduleBadge: "Takim i Shpejtë",
    scheduleSubtitle: "Planifikoni një takim direkt. Nëse jeni brenda Shqipërisë, mund të na kontaktoni drejtpërdrejt në WhatsApp për konfirmim të menjëhershëm.",
    selectTopic: "Zgjidhni Çështjen",
    selectMethod: "Metoda e Takimit",
    meetingInPerson: "Takim Fizik (Tiranë)",
    meetingVirtual: "Takim Online (Zoom / Meet)",
    meetingWhatsApp: "Telefonatë / Chat në WhatsApp",
    btnWhatsApp: "Cakto takim në WhatsApp",
    whatsappPreFill: "Përshëndetje Avokat Ernest Shimka, dëshiroj të caktoj një takim konsulence për çështjen tim ligjore rreth: ",
    allRightsReserved: "Të gjitha të drejtat e rezervuara. © 2026 Zyrë Avokatie Ernest Shimka.",
    locationTirana: "Tiranë, Shqipëri",
    lawChambersName: "Zyrë Avokatie Ernest Shimka"
  },
  en: {
    navHome: "Home",
    navAbout: "About Attorney",
    navServices: "Legal Services",
    navContact: "Contact Us",
    navSchedule: "Book Meeting",
    heroTitle: "Legal Defense with Integrity & Expertise",
    heroSubTitle: "Advocate Ernest Shimka",
    heroDescription: "Specialized Advocate in Tax and Employment Law in Albania. Providing strategic counsel and bulletproof legal representation for corporations, local businesses, and individuals.",
    heroCTAContact: "Get in Touch",
    heroCTASchedule: "Book Consultation",
    quoteText: "The law should not be an obstacle to your business, but a solid shield that guarantees its growth and regulatory stability.",
    quoteAuthor: "Ernest Shimka",
    aboutTitle: "About the Advocate",
    aboutBadge: "Profile & Career",
    aboutDegree: "Law Graduate from the Faculty of Law, University of Tirana",
    cvSectionTitle: "Curriculum Vitae",
    cvPersonal: "Personal Details",
    cvEducation: "Education",
    cvExperience: "Professional History",
    cvLanguages: "Languages Spoken",
    cvSkills: "Skills & Systems",
    cvSpecializations: "Qualifications",
    cvAftesi: "Core Interpersonal Skills",
    labelName: "Full Name",
    labelBirth: "Date of Birth",
    labelProfession: "Profession",
    labelEmail: "Email Address",
    labelPhone: "Phone Number",
    labelLocation: "Office Location",
    servicesTitle: "Legal Specialties",
    servicesBadge: "Our Fields",
    servicesSubtitle: "Focused deep expertise in the two core pillars governing modern business operations and staff management.",
    taxLawTitle: "Tax Law Services",
    taxLawDesc: "Tailored tax solutions designed to optimize your financial standing, manage transactions, and represent you in high-stakes disputes.",
    employmentLawTitle: "Employment Law",
    employmentLawDesc: "Proactive compliance auditing, contract negotiation, benefit schemes, and rigorous defense in workplace disputes.",
    viewMoreDetails: "Read details",
    contactTitle: "Contact Us Today",
    contactBadge: "Contact Info",
    contactSubtitle: "Do you have a legal inquiry? Contact our chambers directly by phone, email, or by scheduling an appointment.",
    formName: "Your Full Name",
    formEmail: "Email Address",
    formPhone: "Phone Number",
    formSubject: "Legal Specialty / Subject",
    formMessage: "Inquiry details / Case background",
    formSubmit: "Send Message",
    formSubmitting: "Sending Inquiry...",
    formSuccessMessage: "Your message has been sent successfully! Advocate Ernest Shimka will follow up with you shortly.",
    formErrorMessage: "There was an error sending the message. Please try again.",
    scheduleTitle: "Schedule a Consultation",
    scheduleBadge: "Instant Booking",
    scheduleSubtitle: "Plan your legal consultation. If you reside in Albania, you can initiate a chat on WhatsApp for rapid scheduling.",
    selectTopic: "Choose Legal Topic",
    selectMethod: "Preferred Meeting Mode",
    meetingInPerson: "In-Person (Tirana Office)",
    meetingVirtual: "Virtual Meeting (Zoom / Google Meet)",
    meetingWhatsApp: "WhatsApp Audio Call & Chat",
    btnWhatsApp: "Initiate WhatsApp Booking",
    whatsappPreFill: "Hello Advocate Ernest Shimka, I would like to schedule a professional consultation regarding: ",
    allRightsReserved: "All rights reserved. © 2026 Law Chambers Ernest Shimka.",
    locationTirana: "Tirana, Albania",
    lawChambersName: "Law Chambers Ernest Shimka"
  }
};

export const SERVICES: ServiceDetail[] = [
  {
    id: "tax_law",
    titleAl: "E Drejta Tatimore (Tax Law)",
    titleEn: "Tax Law Services",
    itemsAl: [
      "Tatim Mbi Korporatat (Corporate Tax): Konsulencë mbi strategjitë tatimore dhe strukturën ligjore të sipërmarrjeve.",
      "Tatimi Ndërkombëtar (International Tax): Menaxhimi i transaksioneve ndërkufitare, marrëveshjet për shmangien e taksimit të dyfishtë.",
      "Planifikim Tatimor & Pajtueshmëri Ligjore: Krijimi i strategjive për optimizimin e detyrimeve dhe respektimin e legjislacionit shqiptar.",
      "Çmimet e Transferimit (Transfer Pricing): Sigurimi i përputhshmërisë me rregulloret kombëtare dhe ndërkombëtare mbi transferimin e vlerave.",
      "TVA / VAT / GST: Konsulencë e detajuar mbi Tatimin mbi Vlerën e Shtuar për mallra dhe shërbime kombëtare e rajonale.",
      "Zgjidhja e Mosmarrëveshjeve Tatimore: Përfaqësim ligjor profesional përballë Drejtorisë së Tatimeve dhe në Gjykata Administrativ.",
      "Stimujt & Lehtësirat Tatimore: Ndihmë për bizneset e reja për të përfituar nga lehtësimet dhe financimet shtetërore.",
      "Tatimi i Përfitimeve të Punonjësve: Trajtimi i saktë tatimor i bonuseve, aksioneve dhe paketave të kompensimit."
    ],
    itemsEn: [
      "Corporate Tax: Advisory on high-level corporate structures, tax liability efficiency, and statutory audits.",
      "International Tax: Navigating cross-border operations, tax treaties, transfer risk, and European framework alignment.",
      "Tax Planning & Compliance: Bulletproof strategy compilation to legally optimize tax exposure while remaining strictly compliant.",
      "Transfer Pricing: Ensuring seamless alignment with OECD guidelines, robust documentation, and local reporting requisites.",
      "VAT & Customs Advisory: Addressing complex value-added taxation mechanisms, exemptions, and dispute avoidance.",
      "Tax Disputes Resolution: Forceful representation in administrative appeals against decisions from the Albanian Regional Tax Directorate.",
      "Tax Incentives Assistance: Streamlining claims on localized benefits, specialized economic zones, and high-tech sector subsidies.",
      "Employee Benefits Taxation: Expert structuring of complex C-level compensation, executive bonuses, shares, and fringe benefits."
    ]
  },
  {
    id: "employment_law",
    titleAl: "E Drejta e Punësimit (Employment Law)",
    titleEn: "Employment & Labor Law",
    itemsAl: [
      "Pajtueshmëria e Punës (Labor Compliance): Përshtatja e rregulloreve të brendshme me Kodin e Punës të Republikës së Shqipërisë.",
      "Politikat e Vendit të Punës: Krijimi i udhëzuesve për të drejtat, mbrojtjen nga diskriminimi, dhe rregullat e sigurisë në punë.",
      "Kontratat e Punës (Employment Agreements): Hartim i specializuar i kontratave individuale, kontratave të menaxhimit dhe klauzolave të konfidencialitetit.",
      "Zgjidhja e Konflikteve: Ndërmjetësim dhe mbrojtje në raste të zgjidhjes të njëanshme të kontratës apo kërkesave për dëmshpërblim.",
      "Paketat e Përfitimeve: Këshillim mbi sigurimet shoqërore, bonuset dhe përfitimet pas ndërprerjes së marrëdhënies së punës.",
      "Përfaqësim në Gjykatë: Mbrojtje e interesave të punëdhënësve apo punëmarrësve në gjykatat e rretheve për mosmarrëveshje pune.",
      "Inspektimi i Punës: Ndihmë gjatë kontrolleve nga Inspektorati i Punës për të shmangur penalitetet.",
      "Marrëveshjet Kolektive: Negocimi i kontratave kolektive me sindikatat ose përfaqësuesit e dhomave tregtare."
    ],
    itemsEn: [
      "Labor Law Compliance: Harmonizing employee handbooks and internal systems with the strict requirements of the Albanian Labor Code.",
      "Workplace Operating Policies: Strategic drafting of occupational health, safety manuals, anti-harassment/discrimination policies.",
      "Employment Agreements: Structuring executive compensation terms, non-compete clauses, IP assignments, and confidentiality acts.",
      "Dispute Resolution & Litigation: Expert defense and prosecution in complex wage, wrongful termination, and severance claims.",
      "Employee Benefits Audit: Designing and verifying retirement options, health coverage schemes, and profit-sharing bonuses.",
      "Labor Inspectorate Representation: Guiding clients calmly through regulatory inspections or resolving formal labor union grievances.",
      "Corporate Restructuring & Layoffs: Legally sound workforce reduction strategies, collective dismissal notices, and severance releases.",
      "Collective Bargaining Agreements: Spearheading enterprise-level negotiations with organized trade unions with mutual benefits."
    ]
  }
];

export const CV_EXPERIENCE: CVExperienceItem[] = [
  {
    years: "2024 - Vazhdim",
    roleAl: "Avokat (Licensed Advocate)",
    roleEn: "Attorney-at-Law / Corporate Advocate",
    companyAl: "Oracle Solicitors Albania SHPK",
    companyEn: "Oracle Solicitors Albania LLC"
  },
  {
    years: "2023 - 2024",
    roleAl: "Konsulent Jurist Kombëtar",
    roleEn: "National Legal Advisor",
    companyAl: "Shoqëria Upstream Creative",
    companyEn: "Upstream Creative Company"
  },
  {
    years: "2022 - 2023",
    roleAl: "Mbledhës Detyrimesh në Departamentin e Riskut",
    roleEn: "Risk Debt Recovery Officer",
    companyAl: "IuteCredit Albania (Institucion Financiar jo Bankar)",
    companyEn: "IuteCredit Albania (Licensed Non-Banking Financial Inst.)"
  },
  {
    years: "2021 - 2022",
    roleAl: "Jurist Rezident",
    roleEn: "Resident Corporate Jurist",
    companyAl: "Prodita Sh.p.k.",
    companyEn: "Prodita Sh.p.k."
  },
  {
    years: "2018 - 2020",
    roleAl: "Ekspert Jurist i Kredidhënies & Rikthimit",
    roleEn: "Legal Credit & Recovery Specialist",
    companyAl: "Micro Credit Albania",
    companyEn: "Micro Credit Albania"
  },
  {
    years: "2010 - 2018",
    roleAl: "Jurist Senior / Këshilltar Ligjor",
    roleEn: "Senior Jurist & Legal Advisor",
    companyAl: "Sektori Privat (Kompanitë Tregtare)",
    companyEn: "Private Sector (Various Trading & Construction Firms)"
  },
  {
    years: "2007 - 2010",
    roleAl: "Përmbarues Shtetëror",
    roleEn: "State Bailiff / Judicial Enforcement Officer",
    companyAl: "Zyra e Përmbarimit Gjyqësor (Vlorë, Gjirokastër, Tepelenë)",
    companyEn: "Judicial Enforcement Office (Vlora, Gjirokastra, Tepelena Regions)"
  },
  {
    years: "2006 - 2007",
    roleAl: "Ekspert Jurist rezident",
    roleEn: "Resident Jurist",
    companyAl: "IEVP Tepelenë (Institucioni i Ekzekutimit të Vendimeve Penale - Paraburgimi)",
    companyEn: "Tepelena Penitentiary Facility (IEVP - Detaining Division)"
  }
];
